// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data.DbContexts;

#nullable disable

namespace WebApplication2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920231033_turno")]
    partial class turno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Aspirante", b =>
                {
                    b.Property<int>("IdAspirante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAspirante"));

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdAspiranteEstatus")
                        .HasColumnType("int");

                    b.Property<string>("IdAtendidoPorUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMedioContacto")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("IdAspirante")
                        .HasName("PK__Aspirant__09EE6349C82C95C4");

                    b.HasIndex("IdAspiranteEstatus");

                    b.HasIndex("IdMedioContacto");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdPlan");

                    b.HasIndex("TurnoId");

                    b.ToTable("Aspirante");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.AspiranteConvenio", b =>
                {
                    b.Property<int>("IdAspiranteConvenio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAspiranteConvenio"));

                    b.Property<string>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdAspirante")
                        .HasColumnType("int");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("int");

                    b.HasKey("IdAspiranteConvenio")
                        .HasName("PK__Aspirant__F372F05FD82F39BA");

                    b.HasIndex("IdConvenio");

                    b.HasIndex(new[] { "IdAspirante", "IdConvenio" }, "UQ_Aspirante_Convenio")
                        .IsUnique();

                    b.ToTable("AspiranteConvenio");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.AspiranteEstatus", b =>
                {
                    b.Property<int>("IdAspiranteEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAspiranteEstatus"));

                    b.Property<string>("DescEstatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAspiranteEstatus")
                        .HasName("PK__Aspirant__7B8DBE92EB8DEDF7");

                    b.HasIndex(new[] { "DescEstatus" }, "UQ_AspiranteEstatus")
                        .IsUnique()
                        .HasFilter("[DescEstatus] IS NOT NULL");

                    b.ToTable("AspiranteEstatus");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Campus", b =>
                {
                    b.Property<int>("IdCampus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCampus"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ClaveCampus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdDireccion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCampus")
                        .HasName("PK__Campus__DA49C2DE1E9DB12C");

                    b.HasIndex("IdDireccion");

                    b.HasIndex(new[] { "ClaveCampus" }, "UQ_Campus_Clave")
                        .IsUnique()
                        .HasFilter("[ClaveCampus] IS NOT NULL");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Campus_Nombre")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("Campus");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.CodigoPostal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asentamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("CodigosPostales");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Convenio", b =>
                {
                    b.Property<int>("IdConvenio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConvenio"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ClaveConvenio")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("DescuentoPct")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TipoBeneficio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("IdConvenio")
                        .HasName("PK__Convenio__51CFFF2B890D4417");

                    b.HasIndex(new[] { "ClaveConvenio" }, "UQ__Convenio__A6197EE9ADAF6A0B")
                        .IsUnique()
                        .HasFilter("[ClaveConvenio] IS NOT NULL");

                    b.ToTable("Convenio");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.ConvenioAlcance", b =>
                {
                    b.Property<int>("IdConvenioAlcance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConvenioAlcance"));

                    b.Property<int?>("IdCampus")
                        .HasColumnType("int");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("int");

                    b.Property<int?>("IdPlanEstudios")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("IdConvenioAlcance")
                        .HasName("PK__Convenio__2A4E02C0B88720E9");

                    b.HasIndex("IdCampus");

                    b.HasIndex("IdConvenio");

                    b.HasIndex("IdPlanEstudios");

                    b.ToTable("ConvenioAlcance");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.DiaSemana", b =>
                {
                    b.Property<byte>("IdDiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdDiaSemana")
                        .HasName("PK__DiaSeman__7A209B4EBAF307F1");

                    b.HasIndex(new[] { "Nombre" }, "UQ__DiaSeman__75E3EFCF34622C9D")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("DiaSemana");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Calle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CodigoPostalId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroExterior")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDireccion")
                        .HasName("PK__Direccio__1F8E0C76513A158C");

                    b.HasIndex("CodigoPostalId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Estado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.EstadoCivil", b =>
                {
                    b.Property<int>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCivil"));

                    b.Property<string>("DescEstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoCivil")
                        .HasName("PK__EstadoCi__889DE1B24D585C92");

                    b.HasIndex(new[] { "DescEstadoCivil" }, "UQ_EstadoCivil")
                        .IsUnique()
                        .HasFilter("[DescEstadoCivil] IS NOT NULL");

                    b.ToTable("EstadoCivil");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("IdPlanActual")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdEstudiante")
                        .HasName("PK__Estudian__B5007C24138D11BB");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdPlanActual");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "Matricula" }, "UQ__Estudian__0FB9FB4F890AE66D")
                        .IsUnique()
                        .HasFilter("[Matricula] IS NOT NULL");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.EstudiantePlan", b =>
                {
                    b.Property<int>("IdEstudiantePlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiantePlan"));

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanEstudios")
                        .HasColumnType("int");

                    b.HasKey("IdEstudiantePlan")
                        .HasName("PK__Estudian__1CF83B276A8D49B7");

                    b.HasIndex("IdPlanEstudios");

                    b.HasIndex(new[] { "IdEstudiante", "IdPlanEstudios", "FechaInicio" }, "UQ_EstudiantePlan")
                        .IsUnique();

                    b.ToTable("EstudiantePlan");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("DescGenero")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdGenero")
                        .HasName("PK__Genero__0F8349880F3BC981");

                    b.HasIndex(new[] { "DescGenero" }, "UQ_Genero")
                        .IsUnique()
                        .HasFilter("[DescGenero] IS NOT NULL");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<short>("CapacidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)40);

                    b.Property<int>("IdPeriodoAcademico")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanEstudios")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<byte>("NumeroCuatrimestre")
                        .HasColumnType("tinyint");

                    b.Property<byte>("NumeroGrupo")
                        .HasColumnType("tinyint");

                    b.HasKey("IdGrupo")
                        .HasName("PK__Grupo__303F6FD92351A792");

                    b.HasIndex("IdPeriodoAcademico");

                    b.HasIndex("IdTurno");

                    b.HasIndex(new[] { "IdPlanEstudios", "IdPeriodoAcademico", "NumeroCuatrimestre", "NumeroGrupo" }, "UQ_Grupo_Num")
                        .IsUnique();

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.GrupoMateria", b =>
                {
                    b.Property<int>("IdGrupoMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoMateria"));

                    b.Property<string>("Aula")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Cupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)40);

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdMateriaPlan")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfesor")
                        .HasColumnType("int");

                    b.HasKey("IdGrupoMateria")
                        .HasName("PK__GrupoMat__9D026FCD2F0EA6B3");

                    b.HasIndex("IdMateriaPlan");

                    b.HasIndex("IdProfesor");

                    b.HasIndex(new[] { "IdGrupo", "IdMateriaPlan" }, "UQ_GrupoMateria")
                        .IsUnique();

                    b.ToTable("GrupoMateria");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("Aula")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("HoraFin")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<byte>("IdDiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdGrupoMateria")
                        .HasColumnType("int");

                    b.HasKey("IdHorario")
                        .HasName("PK__Horario__1539229BCC12B082");

                    b.HasIndex("IdDiaSemana");

                    b.HasIndex(new[] { "IdGrupoMateria", "IdDiaSemana", "HoraInicio", "HoraFin" }, "UQ_Horario")
                        .IsUnique();

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<decimal?>("CalificacionFinal")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Inscrito");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupoMateria")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion")
                        .HasName("PK__Inscripc__A122F2BF81A0DA45");

                    b.HasIndex("IdGrupoMateria");

                    b.HasIndex(new[] { "IdEstudiante", "IdGrupoMateria" }, "UQ_Inscripcion")
                        .IsUnique();

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Clave")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Creditos")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<byte>("HorasPractica")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HorasTeoria")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdMateria")
                        .HasName("PK__Materia__EC17467041102790");

                    b.HasIndex(new[] { "Clave" }, "UQ__Materia__E8181E1169244C5A")
                        .IsUnique()
                        .HasFilter("[Clave] IS NOT NULL");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MateriaPlan", b =>
                {
                    b.Property<int>("IdMateriaPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateriaPlan"));

                    b.Property<byte>("Cuatrimestre")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EsOptativa")
                        .HasColumnType("bit");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanEstudios")
                        .HasColumnType("int");

                    b.HasKey("IdMateriaPlan")
                        .HasName("PK__MateriaP__216FB17FE2CA7B4E");

                    b.HasIndex("IdMateria");

                    b.HasIndex(new[] { "IdPlanEstudios", "IdMateria" }, "UQ_MateriaPlan")
                        .IsUnique();

                    b.ToTable("MateriaPlan");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MedioContacto", b =>
                {
                    b.Property<int>("IdMedioContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedioContacto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescMedio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMedioContacto")
                        .HasName("PK__MedioCon__3E86CE3C31C937DB");

                    b.ToTable("MedioContacto");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Municipio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.NivelEducativo", b =>
                {
                    b.Property<int>("IdNivelEducativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivelEducativo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescNivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNivelEducativo")
                        .HasName("PK__NivelEdu__5035CA164D3A42BB");

                    b.HasIndex(new[] { "DescNivelEducativo" }, "UQ_NivelEducativo")
                        .IsUnique()
                        .HasFilter("[DescNivelEducativo] IS NOT NULL");

                    b.ToTable("NivelEducativo");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Periodicidad", b =>
                {
                    b.Property<int>("IdPeriodicidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodicidad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DescPeriodicidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("MesesPorPeriodo")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PeriodosPorAnio")
                        .HasColumnType("tinyint");

                    b.HasKey("IdPeriodicidad")
                        .HasName("PK__Periodic__DA476CCD8B84E741");

                    b.HasIndex(new[] { "DescPeriodicidad" }, "UQ_Periodicidad")
                        .IsUnique()
                        .HasFilter("[DescPeriodicidad] IS NOT NULL");

                    b.ToTable("Periodicidad");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("IdPeriodoAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodoAcademico"));

                    b.Property<string>("Clave")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdPeriodicidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPeriodoAcademico")
                        .HasName("PK__PeriodoA__E57AB387D551DE0A");

                    b.HasIndex("IdPeriodicidad");

                    b.HasIndex(new[] { "Clave" }, "UQ__PeriodoA__E8181E117466779A")
                        .IsUnique()
                        .HasFilter("[Clave] IS NOT NULL");

                    b.ToTable("PeriodoAcademico");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Curp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IdDireccion")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoCivil")
                        .HasColumnType("int");

                    b.Property<int?>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPersona")
                        .HasName("PK__Persona__2EC8D2AC48F4B00B");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdGenero");

                    b.HasIndex(new[] { "Curp" }, "UQ_Persona_CURP")
                        .IsUnique()
                        .HasFilter("[Curp] IS NOT NULL");

                    b.HasIndex(new[] { "Correo" }, "UQ_Persona_Email")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.HasIndex(new[] { "Rfc" }, "UQ_Persona_RFC")
                        .IsUnique()
                        .HasFilter("[Rfc] IS NOT NULL");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PlanEstudios", b =>
                {
                    b.Property<int>("IdPlanEstudios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanEstudios"));

                    b.Property<string>("ClavePlanEstudios")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DuracionMeses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(48);

                    b.Property<int>("IdCampus")
                        .HasColumnType("int");

                    b.Property<int>("IdNivelEducativo")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodicidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdProgramaEstudios")
                        .HasColumnType("int");

                    b.Property<int>("MinimaAprobatoriaFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(70);

                    b.Property<int>("MinimaAprobatoriaParcial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("NombrePlanEstudios")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("PermiteAdelantar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RVOE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdPlanEstudios")
                        .HasName("PK__PlanEstu__C60618471021EFD8");

                    b.HasIndex("IdCampus");

                    b.HasIndex("IdNivelEducativo");

                    b.HasIndex("IdPeriodicidad");

                    b.HasIndex(new[] { "ClavePlanEstudios" }, "UQ_PlanEstudios")
                        .IsUnique()
                        .HasFilter("[ClavePlanEstudios] IS NOT NULL");

                    b.ToTable("PlanEstudios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("EmailInstitucional")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("NoEmpleado")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdProfesor")
                        .HasName("PK__Profesor__C377C3A119E36880");

                    b.HasIndex("IdPersona");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "NoEmpleado" }, "UQ__Profesor__82F7575B30F93488")
                        .IsUnique()
                        .HasFilter("[NoEmpleado] IS NOT NULL");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Clave")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTurno")
                        .HasName("PK__Turno__C1ECF79ACE66190F");

                    b.HasIndex(new[] { "Clave" }, "UQ__Turno__E8181E11A9929118")
                        .IsUnique()
                        .HasFilter("[Clave] IS NOT NULL");

                    b.ToTable("Turno");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Aspirante", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.AspiranteEstatus", "IdAspiranteEstatusNavigation")
                        .WithMany("Aspirante")
                        .HasForeignKey("IdAspiranteEstatus")
                        .IsRequired()
                        .HasConstraintName("FK_Aspirante_Estatus");

                    b.HasOne("WebApplication2.Core.Models.MedioContacto", "IdMedioContactoNavigation")
                        .WithMany("Aspirante")
                        .HasForeignKey("IdMedioContacto")
                        .IsRequired()
                        .HasConstraintName("FK_Aspirante_Medio");

                    b.HasOne("WebApplication2.Core.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Aspirante")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK_Aspirante_Persona");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanNavigation")
                        .WithMany("Aspirante")
                        .HasForeignKey("IdPlan")
                        .IsRequired()
                        .HasConstraintName("FK_Aspirante_Plan");

                    b.HasOne("WebApplication2.Core.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId");

                    b.Navigation("IdAspiranteEstatusNavigation");

                    b.Navigation("IdMedioContactoNavigation");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("IdPlanNavigation");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.AspiranteConvenio", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Aspirante", "IdAspiranteNavigation")
                        .WithMany("AspiranteConvenio")
                        .HasForeignKey("IdAspirante")
                        .IsRequired()
                        .HasConstraintName("FK_AspConv_Aspirante");

                    b.HasOne("WebApplication2.Core.Models.Convenio", "IdConvenioNavigation")
                        .WithMany("AspiranteConvenio")
                        .HasForeignKey("IdConvenio")
                        .IsRequired()
                        .HasConstraintName("FK_AspConv_Convenio");

                    b.Navigation("IdAspiranteNavigation");

                    b.Navigation("IdConvenioNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Campus", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("Campus")
                        .HasForeignKey("IdDireccion")
                        .HasConstraintName("FK_Campus_Direccion");

                    b.Navigation("IdDireccionNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.CodigoPostal", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Municipio", "Municipio")
                        .WithMany("CodigosPostales")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.ConvenioAlcance", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Campus", "IdCampusNavigation")
                        .WithMany("ConvenioAlcance")
                        .HasForeignKey("IdCampus")
                        .HasConstraintName("FK_ConvAlc_Campus");

                    b.HasOne("WebApplication2.Core.Models.Convenio", "IdConvenioNavigation")
                        .WithMany("ConvenioAlcance")
                        .HasForeignKey("IdConvenio")
                        .IsRequired()
                        .HasConstraintName("FK_ConvAlc_Convenio");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanEstudiosNavigation")
                        .WithMany("ConvenioAlcance")
                        .HasForeignKey("IdPlanEstudios")
                        .HasConstraintName("FK_ConvAlc_Plan");

                    b.Navigation("IdCampusNavigation");

                    b.Navigation("IdConvenioNavigation");

                    b.Navigation("IdPlanEstudiosNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Direccion", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoPostal");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Estudiante", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Estudiante")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Estudiante_Persona");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanActualNavigation")
                        .WithMany("Estudiante")
                        .HasForeignKey("IdPlanActual")
                        .HasConstraintName("FK_Estudiante_Plan");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("IdPlanActualNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.EstudiantePlan", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("EstudiantePlan")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("FK_EstudiantePlan_Estudiante");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanEstudiosNavigation")
                        .WithMany("EstudiantePlan")
                        .HasForeignKey("IdPlanEstudios")
                        .IsRequired()
                        .HasConstraintName("FK_EstudiantePlan_Plan");

                    b.Navigation("IdEstudianteNavigation");

                    b.Navigation("IdPlanEstudiosNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Grupo", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.PeriodoAcademico", "IdPeriodoAcademicoNavigation")
                        .WithMany("Grupo")
                        .HasForeignKey("IdPeriodoAcademico")
                        .IsRequired()
                        .HasConstraintName("FK_Grupo_Periodo");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanEstudiosNavigation")
                        .WithMany("Grupo")
                        .HasForeignKey("IdPlanEstudios")
                        .IsRequired()
                        .HasConstraintName("FK_Grupo_Plan");

                    b.HasOne("WebApplication2.Core.Models.Turno", "IdTurnoNavigation")
                        .WithMany("Grupo")
                        .HasForeignKey("IdTurno")
                        .IsRequired()
                        .HasConstraintName("FK_Grupo_Turno");

                    b.Navigation("IdPeriodoAcademicoNavigation");

                    b.Navigation("IdPlanEstudiosNavigation");

                    b.Navigation("IdTurnoNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.GrupoMateria", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Grupo", "IdGrupoNavigation")
                        .WithMany("GrupoMateria")
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK_GrupoMateria_Grupo");

                    b.HasOne("WebApplication2.Core.Models.MateriaPlan", "IdMateriaPlanNavigation")
                        .WithMany("GrupoMateria")
                        .HasForeignKey("IdMateriaPlan")
                        .IsRequired()
                        .HasConstraintName("FK_GrupoMateria_MatPlan");

                    b.HasOne("WebApplication2.Core.Models.Profesor", "IdProfesorNavigation")
                        .WithMany("GrupoMateria")
                        .HasForeignKey("IdProfesor")
                        .HasConstraintName("FK_GrupoMateria_Profesor");

                    b.Navigation("IdGrupoNavigation");

                    b.Navigation("IdMateriaPlanNavigation");

                    b.Navigation("IdProfesorNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Horario", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.DiaSemana", "IdDiaSemanaNavigation")
                        .WithMany("Horario")
                        .HasForeignKey("IdDiaSemana")
                        .IsRequired()
                        .HasConstraintName("FK_Horario_Dia");

                    b.HasOne("WebApplication2.Core.Models.GrupoMateria", "IdGrupoMateriaNavigation")
                        .WithMany("Horario")
                        .HasForeignKey("IdGrupoMateria")
                        .IsRequired()
                        .HasConstraintName("FK_Horario_GrupoMat");

                    b.Navigation("IdDiaSemanaNavigation");

                    b.Navigation("IdGrupoMateriaNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Inscripcion", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("Inscripcion")
                        .HasForeignKey("IdEstudiante")
                        .IsRequired()
                        .HasConstraintName("FK_Inscripcion_Estudiante");

                    b.HasOne("WebApplication2.Core.Models.GrupoMateria", "IdGrupoMateriaNavigation")
                        .WithMany("Inscripcion")
                        .HasForeignKey("IdGrupoMateria")
                        .IsRequired()
                        .HasConstraintName("FK_Inscripcion_GrupoMateria");

                    b.Navigation("IdEstudianteNavigation");

                    b.Navigation("IdGrupoMateriaNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MateriaPlan", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Materia", "IdMateriaNavigation")
                        .WithMany("MateriaPlan")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_MateriaPlan_Materia");

                    b.HasOne("WebApplication2.Core.Models.PlanEstudios", "IdPlanEstudiosNavigation")
                        .WithMany("MateriaPlan")
                        .HasForeignKey("IdPlanEstudios")
                        .IsRequired()
                        .HasConstraintName("FK_MateriaPlan_Plan");

                    b.Navigation("IdMateriaNavigation");

                    b.Navigation("IdPlanEstudiosNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Municipio", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PeriodoAcademico", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Periodicidad", "IdPeriodicidadNavigation")
                        .WithMany("PeriodoAcademico")
                        .HasForeignKey("IdPeriodicidad")
                        .IsRequired()
                        .HasConstraintName("FK_Periodo_Periodicidad");

                    b.Navigation("IdPeriodicidadNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Persona", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdDireccion")
                        .HasConstraintName("FK_Persona_Direccion");

                    b.HasOne("WebApplication2.Core.Models.EstadoCivil", "IdEstadoCivilNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdEstadoCivil")
                        .HasConstraintName("FK_Persona_EstadoCivil");

                    b.HasOne("WebApplication2.Core.Models.Genero", "IdGeneroNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdGenero")
                        .HasConstraintName("FK_Persona_Genero");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("IdEstadoCivilNavigation");

                    b.Navigation("IdGeneroNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PlanEstudios", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Campus", "IdCampusNavigation")
                        .WithMany("PlanEstudios")
                        .HasForeignKey("IdCampus")
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Campus");

                    b.HasOne("WebApplication2.Core.Models.NivelEducativo", "IdNivelEducativoNavigation")
                        .WithMany("PlanEstudios")
                        .HasForeignKey("IdNivelEducativo")
                        .IsRequired()
                        .HasConstraintName("FK_Plan_NivelEducativo");

                    b.HasOne("WebApplication2.Core.Models.Periodicidad", "IdPeriodicidadNavigation")
                        .WithMany("PlanEstudios")
                        .HasForeignKey("IdPeriodicidad")
                        .IsRequired()
                        .HasConstraintName("FK_Plan_Periodicidad");

                    b.Navigation("IdCampusNavigation");

                    b.Navigation("IdNivelEducativoNavigation");

                    b.Navigation("IdPeriodicidadNavigation");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Profesor", b =>
                {
                    b.HasOne("WebApplication2.Core.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Profesor")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Profesor_Persona");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Aspirante", b =>
                {
                    b.Navigation("AspiranteConvenio");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.AspiranteEstatus", b =>
                {
                    b.Navigation("Aspirante");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Campus", b =>
                {
                    b.Navigation("ConvenioAlcance");

                    b.Navigation("PlanEstudios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Convenio", b =>
                {
                    b.Navigation("AspiranteConvenio");

                    b.Navigation("ConvenioAlcance");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.DiaSemana", b =>
                {
                    b.Navigation("Horario");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Direccion", b =>
                {
                    b.Navigation("Campus");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.EstadoCivil", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Estudiante", b =>
                {
                    b.Navigation("EstudiantePlan");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Genero", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Grupo", b =>
                {
                    b.Navigation("GrupoMateria");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.GrupoMateria", b =>
                {
                    b.Navigation("Horario");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Materia", b =>
                {
                    b.Navigation("MateriaPlan");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MateriaPlan", b =>
                {
                    b.Navigation("GrupoMateria");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.MedioContacto", b =>
                {
                    b.Navigation("Aspirante");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Municipio", b =>
                {
                    b.Navigation("CodigosPostales");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.NivelEducativo", b =>
                {
                    b.Navigation("PlanEstudios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Periodicidad", b =>
                {
                    b.Navigation("PeriodoAcademico");

                    b.Navigation("PlanEstudios");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Persona", b =>
                {
                    b.Navigation("Aspirante");

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.PlanEstudios", b =>
                {
                    b.Navigation("Aspirante");

                    b.Navigation("ConvenioAlcance");

                    b.Navigation("Estudiante");

                    b.Navigation("EstudiantePlan");

                    b.Navigation("Grupo");

                    b.Navigation("MateriaPlan");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Profesor", b =>
                {
                    b.Navigation("GrupoMateria");
                });

            modelBuilder.Entity("WebApplication2.Core.Models.Turno", b =>
                {
                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
